- name: Install Jenkins Java Worker Node
  hosts: java-worker
  connection: ssh
  become: true

  roles:
    - role: java

    - role: maven
      maven_version: '3.6.0'

  tasks:
    - name: Install additional requirements
      package:
        name:
          - ant
          - zip
          - unzip
          - bzip2
          - git
        state: present

    - name: Register Jenkins Worker with Master
      jenkins_script:
        script: "{{ lookup('template', 'templates/jenkins-worker-registration.groovy.j2') }}"
        url: "{{ jenkins_master }}"
        user: jenkins
        password: jenkins
        validate_certs: no
